services:
  - type: web
    name: api-gateway
    env: docker
    dockerfilePath: apps/api-gateway/Dockerfile
    plan: free
    branch: main
    region: oregon
    envVars:
      - key: PORT
        value: "3000"
    instanceCount: 1
    autoDeploy: true

  - type: web
    name: sailor-service
    env: docker
    dockerfilePath: apps/sailor-service/Dockerfile
    plan: free
    branch: main
    region: oregon
    envVars:
      - key: PORT
        value: "3001"
    instanceCount: 1
    autoDeploy: true

  - type: web
    name: schedule-service
    env: docker
    dockerfilePath: apps/schedule-service/Dockerfile
    plan: free
    branch: main
    region: oregon
    envVars:
      - key: PORT
        value: "3002"
    instanceCount: 1
    autoDeploy: true
